version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: ⬆
    groups:
      actions-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: uv
    directory: /backend
    schedule:
      interval: weekly
    commit-message:
      prefix: ⬆
    groups:
      backend-minor-patch:
        patterns:
          - "*"
        exclude-patterns:
          - "ty"
          - "ruff"
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    commit-message:
      prefix: ⬆
    ignore:
      - dependency-name: typescript
        update-types:
          - version-update:semver-major
    groups:
      frontend-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
